-- MySQL Script generated by MySQL Workbench
-- Sun May 16 17:13:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ICS199GreenGrocerDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ICS199GreenGrocerDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ICS199GreenGrocerDB` DEFAULT CHARACTER SET utf8 ;
USE `ICS199GreenGrocerDB` ;

-- -----------------------------------------------------
-- Table `ICS199GreenGrocerDB`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ICS199GreenGrocerDB`.`Users` (
  `USER_ID` VARCHAR(45) NOT NULL,
  `Administrator` TINYINT NULL,
  `User_name` VARCHAR(45) NULL,
  `Encrypted_password` VARCHAR(60) NULL,
  `Firstname` VARCHAR(45) NULL,
  `Lastname` VARCHAR(45) NULL,
  `Email_Address` VARCHAR(45) NULL,
  `Home_Address` VARCHAR(45) NULL,
  `Phone_Number` VARCHAR(45) NULL,
  `Postal_Code` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `legalagreement` TINYINT NULL,
  PRIMARY KEY (`USER_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ICS199GreenGrocerDB`.`Order_History`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ICS199GreenGrocerDB`.`Order_History` (
  `ORDER_ID` VARCHAR(45) NOT NULL,
  `USER_ID` VARCHAR(45) NOT NULL,
  `Status_Order` VARCHAR(45) NULL,
  `Date_Order` VARCHAR(45) NULL,
  PRIMARY KEY (`ORDER_ID`, `USER_ID`),
  INDEX `fk_Order_History_Users_idx` (`USER_ID` ASC),
  CONSTRAINT `fk_Order_History_Users`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `ICS199GreenGrocerDB`.`Users` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ICS199GreenGrocerDB`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ICS199GreenGrocerDB`.`Categories` (
  `Name_Category`  VARCHAR(45) NOT NULL,
  `Category_Id` INT NULL,
  PRIMARY KEY (`Name_Category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ICS199GreenGrocerDB`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ICS199GreenGrocerDB`.`Product` (
  `PRODUCT_ID` VARCHAR(45) NOT NULL,
  `Information_product` VARCHAR(45) NULL,
  `Name_Product` VARCHAR(45) NULL,
  `Price_Product` VARCHAR(45) NULL,
  `Image_Product` VARCHAR(100) NULL,
  `Categories` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PRODUCT_ID`, `Categories`),
  INDEX `fk_Product_Categories1_idx` (`Categories` ASC),
  CONSTRAINT `fk_Product_Categories1`
    FOREIGN KEY (`Categories`)
    REFERENCES `ICS199GreenGrocerDB`.`Categories` (`Name_Category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ICS199GreenGrocerDB`.`Shopping_Cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ICS199GreenGrocerDB`.`Shopping_Cart` (
  `PRODUCT_ID` VARCHAR(45) NOT NULL,
  `USER_ID` VARCHAR(45) NOT NULL,
  `Quantity_Product` VARCHAR(45) NULL,
  PRIMARY KEY (`PRODUCT_ID`, `USER_ID`),
  INDEX `fk_Shopping_Cart_Users1_idx` (`USER_ID` ASC),
  INDEX `fk_Shopping_Cart_Product1_idx` (`PRODUCT_ID` ASC),
  CONSTRAINT `fk_Shopping_Cart_Users1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `ICS199GreenGrocerDB`.`Users` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shopping_Cart_Product1`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `ICS199GreenGrocerDB`.`Product` (`PRODUCT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ICS199GreenGrocerDB`.`Order_Specifics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ICS199GreenGrocerDB`.`Order_Specifics` (
  `ORDER_ID` VARCHAR(45) NOT NULL,
  `PRODUCT_ID` VARCHAR(45) NOT NULL,
  `Price_Items` INT(30) NULL,
  `Product_Quantity` INT(30) NULL,
  PRIMARY KEY (`ORDER_ID`, `PRODUCT_ID`),
  INDEX `fk_Order_Specifics_Product1_idx` (`PRODUCT_ID` ASC),
  INDEX `fk_Order_Specifics_Order_History1_idx` (`ORDER_ID` ASC),
  CONSTRAINT `fk_Order_Specifics_Product1`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `ICS199GreenGrocerDB`.`Product` (`PRODUCT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Specifics_Order_History1`
    FOREIGN KEY (`ORDER_ID`)
    REFERENCES `ICS199GreenGrocerDB`.`Order_History` (`ORDER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


CREATE SEQUENCE user_id_sequence
start with 10000
increment by 1
minvalue 10000
maxvalue 100000
nocycle;

CREATE SEQUENCE product_id_sequence
start with 1
increment by 1
minvalue 1
maxvalue 100000
nocycle;

ALTER TABLE users
ADD CONSTRAINT UC_USERID UNIQUE (User_name);

CREATE SEQUENCE order_id_sequence
start with 1
increment by 1
minvalue 1
maxvalue 100000
nocycle; 

ALTER TABLE order_history
ADD CONSTRAINT order_id_sequence UNIQUE (ORDER_ID);
